import { z } from 'zod';

import { apiOk, handleApiError } from '@/lib/api';
import { resolveOwnLink } from '@/lib/aniga/link-verify';
import { requireUser } from '@/lib/auth/guards';
import { enforceRateLimit } from '@/lib/rate-limit';
import { getSupabaseAdmin } from '@/lib/supabase/server';

/**
 * POST /api/me/profile/links/verify — start tier 3 of the Xaqiiq ladder.
 *
 * Issues (or re-returns) the nonce the member pastes onto their page and puts
 * the link into `pending`. The token is generated by the DB default and is
 * withheld from the `authenticated` column grant, so this route is the ONLY
 * way it reaches a browser — and it only ever reaches the owner, because
 * `resolveOwnLink` requires the URL to already be on the caller's profile.
 *
 * An already-verified link is returned untouched. Re-issuing would drop it back
 * to `pending`, which reads to a visitor as "the check was revoked" for what is
 * really a member tapping the button twice.
 */

const postSchema = z.object({ url: z.string().trim().min(1).max(2048) }).strict();

export async function POST(request: Request): Promise<Response> {
  try {
    const ctx = await requireUser();
    const input = postSchema.parse(await request.json());

    await enforceRateLimit(`linkverify:${ctx.appUser.id}`, { max: 30, windowSeconds: 3600 });

    const link = await resolveOwnLink(ctx, input.url);
    const admin = getSupabaseAdmin();

    const { data: existing, error: readError } = await admin
      .from('profile_link_meta')
      .select('verification_status, verification_token')
      .eq('user_id', ctx.appUser.id)
      .eq('url_key', link.urlKey)
      .maybeSingle();
    if (readError) throw new Error(`link meta lookup failed: ${readError.message}`);

    if (existing?.verification_status === 'verified') {
      return apiOk({
        urlKey: link.urlKey,
        token: existing.verification_token,
        status: 'verified' as const,
      });
    }

    const { data: saved, error: writeError } = existing
      ? await admin
          .from('profile_link_meta')
          .update({
            verification_status: 'pending',
            verified_at: null,
            updated_at: new Date().toISOString(),
          })
          .eq('user_id', ctx.appUser.id)
          .eq('url_key', link.urlKey)
          .select('verification_status, verification_token')
          .single()
      : await admin
          .from('profile_link_meta')
          .insert({
            user_id: ctx.appUser.id,
            url_key: link.urlKey,
            verification_status: 'pending',
          })
          .select('verification_status, verification_token')
          .single();
    if (writeError) throw new Error(`link verification start failed: ${writeError.message}`);

    return apiOk({
      urlKey: link.urlKey,
      token: saved.verification_token,
      status: saved.verification_status,
    });
  } catch (error) {
    return handleApiError(error);
  }
}
