/**
 * TEST-COMMUNITY personas (pre-launch test phase — NEVER the production DB).
 *
 * A curated miniature society of 60 fake members + 2 extra AI helper accounts
 * (beside the standard `xidig_ai`), used to exercise UX, onboarding, Plaza,
 * Labs, DMs, notifications, moderation, search, discovery, membership states,
 * region gating and low-bandwidth behaviour before real users arrive.
 *
 * This dataset is deliberately OUT-OF-BAND from the launch-density seed
 * (`../data.ts`): that seed is governed by the locked "no fake people" rule and
 * the `seed_runs`/`seed_entities` registry. Test-community accounts are fake
 * people BY DESIGN, for a non-production database only. The runner refuses any
 * database that is not verified non-production (lib/seed/target-guard.ts),
 * whatever NODE_ENV says. History: the old NODE_ENV-only guard let this dataset
 * reach the live production DB (the Supabase project labelled "Dev Xidig App",
 * tbdryvhxxiqadseuxclm), found by the 12 Sep 2026 audit. Every account it
 * creates is marked users.is_test (quarantined from organic proof).
 *
 * Login convention (documented in the generated seed README):
 *   email    = `${handle}@example.com`
 *   password = getTestCommunityPassword() (same for every account, from env)
 */

export const TEST_COMMUNITY_LABEL = 'test-community-v1';

/** Shared password for every test account, supplied via env so no plaintext
 * credential lives in committable source. Pick something memorable that
 * satisfies GoTrue's 6-char minimum; re-running the seeder resets every
 * existing test account to the configured value. Never falls back to a
 * default — unset env fails fast with setup instructions. */
export function getTestCommunityPassword(): string {
  const password =
    process.env.TEST_COMMUNITY_PASSWORD ?? process.env.XIDIG_TEST_COMMUNITY_PASSWORD;
  if (!password) {
    throw new Error(
      'Test-community seeder: no shared test password configured. Set ' +
        'TEST_COMMUNITY_PASSWORD (or XIDIG_TEST_COMMUNITY_PASSWORD) in apps/web/.env.local ' +
        '— any GoTrue-valid password (6+ chars) — then restart the dev server and retry. ' +
        'There is deliberately no default.',
    );
  }
  return password;
}

export type AgeBand = '18-24' | '25-34' | '35-44' | '45-54' | '55-64' | '65+';
export type Completeness = 'full' | 'partial' | 'minimal' | 'bare';
export type ModerationRisk = 'normal' | 'heated' | 'spammy' | 'needs_review';
export type OpenToKind =
  | 'cofounding'
  | 'hiring'
  | 'hire_me'
  | 'investing'
  | 'mentoring'
  | 'collaborating';

export interface TestPersona {
  /** Stable natural key; also the profile handle and the email local part. */
  handle: string;
  displayName: string;
  ageBand: AgeBand;
  /** ISO-3166 alpha-2 (matches profiles.location_country usage). */
  locationCountry: string | null;
  locationCity: string | null;
  timezone: string | null;
  /** Spoken languages (documentation; preferred UI language is `preferredLanguage`). */
  languages: string[];
  preferredLanguage: 'en' | 'so';
  lowBandwidth: boolean;
  /** One-line intro (README + short bios). */
  oneLine: string;
  /** Full bio; null = no bio (profile-completeness testing). */
  bio: string | null;
  skills: string[];
  /** Drives tag follows + content themes (not a DB column). */
  interests: string[];
  lanes: string[];
  openTo: OpenToKind[];
  /** Free-text availability note woven into bios/README (no DB column). */
  availability: string;
  membershipTier: 'free' | 'supporter';
  role: 'member' | 'mod' | 'admin';
  isVerifier: boolean;
  verification: 'unverified' | 'community_verified' | 'identity_verified';
  accountStatus: 'active' | 'suspended' | 'deactivated';
  completeness: Completeness;
  hasAvatar: boolean;
  hasBanner: boolean;
  avatarPrompt: string;
  bannerPrompt: string;
  postingStyle: string;
  labInterests: string[];
  dmStyle: string;
  moderationRisk: ModerationRisk;
  /** Relative activity level: drives volume of posts/comments/reactions. */
  activity: 'high' | 'medium' | 'low' | 'lurker' | 'none';
  testPurpose: string;
}

/** Extra AI helper accounts (beside the standard `xidig_ai` actor, which the
 * runner provisions via the existing idempotent `provisionAiAssistant`).
 * All are badged `is_ai`, never pretend to be human, hold no roles/grants, and
 * author only `source: 'ai'` content. */
export interface TestAiHelper {
  handle: string;
  displayName: string;
  bio: string;
  preferredLanguage: 'en' | 'so';
  purpose: string;
}

export const TEST_AI_HELPERS: TestAiHelper[] = [
  {
    handle: 'caawiye_ai',
    displayName: 'Caawiye AI',
    bio: 'Kaaliyaha AI ee Xidig — waxaan ku jawaabaa su’aalaha Plaza, waxaan soo jeediyaa calaamado (tags), waxaanan ku caawiyaa bilowga. Waxa aan qoro oo dhan waxaa lagu calaamadeeyaa AI. / Xidig’s AI helper — I answer Plaza Asks, suggest tags, and help new members get started. Everything I post is labelled AI.',
    preferredLanguage: 'so',
    purpose:
      'Somali-first Ask answering, tag suggestions, onboarding assistance. Tests the AI badge + source labels in a Somali-language context.',
  },
  {
    handle: 'warshad_ai',
    displayName: 'Warshad AI',
    bio: 'Xidig’s Labs assistant (AI). I summarise Lab build-logs and draft digest-style roundups so humans can skim what happened. Everything I post is labelled AI-assisted.',
    preferredLanguage: 'en',
    purpose:
      'Lab-update summaries + digest-style drafts. Tests `source: ai` lab_updates and AI labels inside Spaces.',
  },
];

/**
 * The 60 human personas. Ordering is by cluster:
 * staff(4) → tech(8) → agri/climate(6) → women's co-op(5) → diaspora business(6)
 * → health(4) → education(5) → trades/logistics(6) → culture/media(4)
 * → civic(5) → moderation-test(4) → edge cases(3).
 */
export const TEST_PERSONAS: TestPersona[] = [
  // ───────────────────────── staff (admin / mods / verifier) ─────────────────
  {
    handle: 'warsame_admin',
    displayName: 'Warsame Cali Geedi',
    ageBand: '35-44',
    locationCountry: 'SO',
    locationCity: 'Mogadishu',
    timezone: 'Africa/Mogadishu',
    languages: ['so', 'en'],
    preferredLanguage: 'en',
    lowBandwidth: false,
    oneLine: 'Platform admin for the test community.',
    bio: 'Admin account for the Xidig test community. I keep the lights on, review flagged content, and run the seed/admin dashboards. Ping a mod first — I am the escalation path, not the front desk.',
    skills: ['project management', 'devops'],
    interests: ['governance', 'community'],
    lanes: ['professional-services'],
    openTo: [],
    availability: 'Weekdays, Mogadishu hours.',
    membershipTier: 'supporter',
    role: 'admin',
    isVerifier: false,
    verification: 'identity_verified',
    accountStatus: 'active',
    completeness: 'full',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Confident Somali man, 38, short beard, navy blazer, warm office light, head-and-shoulders portrait.',
    bannerPrompt: 'Mogadishu skyline at dusk with the Indian Ocean behind, deep blue tones.',
    postingStyle: 'Rare, official announcements; pins weekly highlights.',
    labInterests: [],
    dmStyle: 'Short, procedural replies.',
    moderationRisk: 'normal',
    activity: 'low',
    testPurpose: 'Admin dashboards, seed admin UI, pinning, governance log, audit trail attribution.',
  },
  {
    handle: 'hodan_mod',
    displayName: 'Hodan Cabdi Xasan',
    ageBand: '25-34',
    locationCountry: 'GB',
    locationCity: 'London',
    timezone: 'Europe/London',
    languages: ['en', 'so'],
    preferredLanguage: 'en',
    lowBandwidth: false,
    oneLine: 'Community moderator, London diaspora.',
    bio: 'Moderator on Xidig. Community organiser in East London by day. I care about keeping this a place where a first-time poster feels safe. Report first, argue later — we read everything.',
    skills: ['content writing', 'public speaking', 'leadership'],
    interests: ['community', 'safety', 'events'],
    lanes: ['nonprofit'],
    openTo: ['mentoring'],
    availability: 'Evenings UK time.',
    membershipTier: 'supporter',
    role: 'mod',
    isVerifier: false,
    verification: 'community_verified',
    accountStatus: 'active',
    completeness: 'full',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Somali woman, early 30s, patterned hijab in teal, friendly direct gaze, soft daylight.',
    bannerPrompt: 'East London street market with fabric stalls, documentary style.',
    postingStyle: 'Welcoming replies, de-escalation, occasional community-guidelines reminders.',
    labInterests: [],
    dmStyle: 'Warm but boundaried; never discusses cases in DM.',
    moderationRisk: 'normal',
    activity: 'medium',
    testPurpose: 'Mod queue (reports/appeals/HITL), mod actions on content, event hosting rights, recusal rules.',
  },
  {
    handle: 'cumar_mod',
    displayName: 'Cumar Maxamed Faarax',
    ageBand: '35-44',
    locationCountry: 'US',
    locationCity: 'Minneapolis',
    timezone: 'America/Chicago',
    languages: ['en', 'so'],
    preferredLanguage: 'en',
    lowBandwidth: false,
    oneLine: 'Moderator; youth-program coordinator in Minneapolis.',
    bio: 'Second moderator. I run youth programs in the Twin Cities and moderate here in the evenings. Fair warning: I have seen every scam format twice.',
    skills: ['teaching', 'leadership'],
    interests: ['youth', 'sports', 'safety'],
    lanes: ['education', 'nonprofit'],
    openTo: ['mentoring'],
    availability: 'US evenings.',
    membershipTier: 'free',
    role: 'mod',
    isVerifier: false,
    verification: 'community_verified',
    accountStatus: 'active',
    completeness: 'full',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Somali-American man, 40, glasses, hoodie with whistle around neck, gym background blurred.',
    bannerPrompt: 'Indoor community sports hall, warm light, kids playing football in the distance.',
    postingStyle: 'Direct, brief; flags scams publicly.',
    labInterests: [],
    dmStyle: 'Terse but helpful.',
    moderationRisk: 'normal',
    activity: 'medium',
    testPurpose: 'Second mod for the appeal-recusal rule (a different mod must review appeals); suspension actions; free-tier mod.',
  },
  {
    handle: 'leyla_verifier',
    displayName: 'Leyla Axmed Nuur',
    ageBand: '25-34',
    locationCountry: 'CA',
    locationCity: 'Toronto',
    timezone: 'America/Toronto',
    languages: ['en', 'so'],
    preferredLanguage: 'en',
    lowBandwidth: false,
    oneLine: 'Identity/business verifier (trusted grant, not a mod).',
    bio: 'I run verification calls for Xidig — a short video chat that confirms you are who you say you are. Ops background in fintech compliance. Verifier, not a moderator: I cannot see reports and mods cannot see recordings.',
    skills: ['finance', 'consulting'],
    interests: ['compliance', 'fintech'],
    lanes: ['fintech', 'professional-services'],
    openTo: [],
    availability: 'Booked slots only.',
    membershipTier: 'free',
    role: 'member',
    isVerifier: true,
    verification: 'identity_verified',
    accountStatus: 'active',
    completeness: 'full',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Somali-Canadian woman, 29, blazer, neutral studio background, professional headshot.',
    bannerPrompt: 'Toronto skyline with CN Tower at golden hour.',
    postingStyle: 'Almost never posts; answers verification questions when tagged.',
    labInterests: [],
    dmStyle: 'Scheduling-bot politeness.',
    moderationRisk: 'normal',
    activity: 'low',
    testPurpose: 'verifier_grants capability separate from mod/admin; verification queue; access-logged recording flow.',
  },

  // ───────────────────────── tech / builders ─────────────────────────
  {
    handle: 'ayaan_dev',
    displayName: 'Ayaan Xuseen Warsame',
    ageBand: '25-34',
    locationCountry: 'SO',
    locationCity: 'Hargeisa',
    timezone: 'Africa/Mogadishu',
    languages: ['so', 'en'],
    preferredLanguage: 'en',
    lowBandwidth: false,
    oneLine: 'Software engineer in Hargeisa; leads the Xawilaad Sandbox Lab.',
    bio: 'Building payment tooling from Hargeisa. Ex-remittance ops, self-taught engineer, now leading the Xawilaad Sandbox Lab here on Xidig. I answer every serious question about learning to code — waan ku faraxsanahay in aan wax baro dadka. DMs open for mentorship.',
    skills: ['software development', 'typescript', 'react', 'node.js', 'sql', 'product management'],
    interests: ['fintech', 'remittance', 'developer-community'],
    lanes: ['fintech', 'telecom'],
    openTo: ['mentoring', 'cofounding', 'collaborating'],
    availability: 'Evenings + weekends, EAT.',
    membershipTier: 'supporter',
    role: 'member',
    isVerifier: false,
    verification: 'community_verified',
    accountStatus: 'active',
    completeness: 'full',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Somali woman, 28, light hijab, laptop stickers visible, co-working space, confident smile.',
    bannerPrompt: 'Hargeisa cityscape with mobile-money kiosks, bright daylight, teal accent.',
    postingStyle: 'Long build-in-public updates, credits others generously, answers Asks in detail.',
    labInterests: ['fintech', 'developer tools'],
    dmStyle: 'Generous mentor, replies with links and homework.',
    moderationRisk: 'normal',
    activity: 'high',
    testPurpose: 'Power user: Lab lead, Supporter, candidate creator, credited answers, high reputation, mentions hub.',
  },
  {
    handle: 'khalid_codes',
    displayName: 'Khaalid Yuusuf Axmed',
    ageBand: '18-24',
    locationCountry: 'SO',
    locationCity: 'Mogadishu',
    timezone: 'Africa/Mogadishu',
    languages: ['so', 'en'],
    preferredLanguage: 'so',
    lowBandwidth: true,
    oneLine: 'Self-taught JavaScript learner, first job hunting.',
    bio: 'Waxaan baranayaa JavaScript iyo React — maalin kasta 2 saacadood. Raadinaya shaqadayda ugu horreysa ee tech. Su’aalo badan ayaan qabaa, samir la kaalaya! (Learning JS/React daily, hunting for my first tech job. I ask a LOT of questions.)',
    skills: ['javascript', 'web development'],
    interests: ['fintech', 'learning', 'football'],
    lanes: ['fintech'],
    openTo: ['hire_me'],
    availability: 'Full-time learner.',
    membershipTier: 'free',
    role: 'member',
    isVerifier: false,
    verification: 'unverified',
    accountStatus: 'active',
    completeness: 'partial',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Young Somali man, 21, headphones around neck, internet-café setting, eager expression.',
    bannerPrompt: 'Code editor glow on a laptop in a dim room.',
    postingStyle: 'Frequent Asks, thanks everyone, marks answers credited.',
    labInterests: ['fintech'],
    dmStyle: 'Enthusiastic, many follow-up questions, sometimes double-texts.',
    moderationRisk: 'normal',
    activity: 'high',
    testPurpose: 'Ask flow + credited answers, low-bandwidth mode, Somali UI, free-tier rate limits, mentee DM thread.',
  },
  {
    handle: 'nasra_sec',
    displayName: 'Nasra Ibraahim Cali',
    ageBand: '25-34',
    locationCountry: 'SE',
    locationCity: 'Stockholm',
    timezone: 'Europe/Stockholm',
    languages: ['sv', 'en', 'so'],
    preferredLanguage: 'en',
    lowBandwidth: false,
    oneLine: 'Security engineer in Stockholm; breaks things politely.',
    bio: 'AppSec engineer. I do threat modelling for a Swedish bank and volunteer security reviews for diaspora projects. Ask me about phishing that targets xawilaad users — it is worse than you think. Opinions mine, disclosure responsible.',
    skills: ['cybersecurity', 'python', 'cloud computing'],
    interests: ['security', 'fintech', 'privacy'],
    lanes: ['fintech', 'professional-services'],
    openTo: ['collaborating', 'mentoring'],
    availability: 'A few evenings a month.',
    membershipTier: 'supporter',
    role: 'member',
    isVerifier: false,
    verification: 'community_verified',
    accountStatus: 'active',
    completeness: 'full',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Somali-Swedish woman, 31, dark blazer, minimalist Scandinavian office, calm expression.',
    bannerPrompt: 'Stockholm waterfront in winter light, muted blue palette.',
    postingStyle: 'Precise, sourced, corrects misinformation without heat.',
    labInterests: ['fintech', 'security'],
    dmStyle: 'Slow to reply, thorough when she does.',
    moderationRisk: 'normal',
    activity: 'medium',
    testPurpose: 'Cybersecurity persona; scam-warning content; Lab core member; endorsements source.',
  },
  {
    handle: 'liibaan_data',
    displayName: 'Liibaan Cismaan Jaamac',
    ageBand: '25-34',
    locationCountry: 'KE',
    locationCity: 'Nairobi',
    timezone: 'Africa/Nairobi',
    languages: ['so', 'en', 'sw'],
    preferredLanguage: 'en',
    lowBandwidth: false,
    oneLine: 'Data analyst in Eastleigh; reads everything, posts rarely.',
    bio: 'Data analyst at a Nairobi logistics firm. Eastleigh raised. Mostly here to read and react — I will comment when I have numbers to add.',
    skills: ['data analysis', 'sql', 'python'],
    interests: ['logistics', 'markets'],
    lanes: ['logistics'],
    openTo: ['hire_me'],
    availability: 'Weekends.',
    membershipTier: 'free',
    role: 'member',
    isVerifier: false,
    verification: 'unverified',
    accountStatus: 'active',
    completeness: 'partial',
    hasAvatar: true,
    hasBanner: false,
    avatarPrompt: 'Somali-Kenyan man, 27, checked shirt, Eastleigh street backdrop, reserved half-smile.',
    bannerPrompt: 'Spreadsheet reflections on glasses, moody desk scene.',
    postingStyle: 'Reacts a lot, rare one-line comments with a statistic.',
    labInterests: ['logistics'],
    dmStyle: 'Reads, answers in one line days later.',
    moderationRisk: 'normal',
    activity: 'lurker',
    testPurpose: 'Quiet-user pattern: reactions without posts, gradient avatar fallback, spam-DM report source.',
  },
  {
    handle: 'sagal_ux',
    displayName: 'Sagal Maxamuud Diiriye',
    ageBand: '25-34',
    locationCountry: 'CA',
    locationCity: 'Toronto',
    timezone: 'America/Toronto',
    languages: ['en', 'so'],
    preferredLanguage: 'en',
    lowBandwidth: false,
    oneLine: 'Product designer; makes forms less painful.',
    bio: 'Product designer at a Canadian health startup. I sketch flows for the Xawilaad Sandbox Lab on weekends. Strong opinions about onboarding screens, weakly held about everything else.',
    skills: ['ux design', 'ui design', 'product design'],
    interests: ['design', 'fintech', 'accessibility'],
    lanes: ['fintech', 'creative-arts'],
    openTo: ['collaborating'],
    availability: 'Weekends.',
    membershipTier: 'supporter',
    role: 'member',
    isVerifier: false,
    verification: 'unverified',
    accountStatus: 'active',
    completeness: 'full',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Somali-Canadian woman, 30, round glasses, colourful headwrap, design studio bokeh.',
    bannerPrompt: 'Wireframe sketches and sticky notes on a whiteboard, bright and playful.',
    postingStyle: 'Posts screenshots-in-words, asks for feedback, runs quick polls.',
    labInterests: ['fintech', 'design'],
    dmStyle: 'Voice-note energy in text form.',
    moderationRisk: 'normal',
    activity: 'medium',
    testPurpose: 'Lab core member, poll creation, design-feedback threads.',
  },
  {
    handle: 'daauud_devops',
    displayName: "Daa'uud Saleebaan Geele",
    ageBand: '35-44',
    locationCountry: 'AE',
    locationCity: 'Dubai',
    timezone: 'Asia/Dubai',
    languages: ['en', 'so', 'ar'],
    preferredLanguage: 'en',
    lowBandwidth: false,
    oneLine: 'DevOps engineer in Dubai; automates everything twice.',
    bio: 'SRE for a Gulf e-commerce platform. Somali-born, Dubai-based. I keep servers boring so founders can be exciting. Happy to review infra plans for community projects.',
    skills: ['devops', 'cloud computing', 'sql'],
    interests: ['infrastructure', 'e-commerce'],
    lanes: ['e-commerce', 'telecom'],
    openTo: ['collaborating'],
    availability: 'Fridays.',
    membershipTier: 'free',
    role: 'member',
    isVerifier: false,
    verification: 'unverified',
    accountStatus: 'active',
    completeness: 'partial',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Somali man, 38, polo shirt, Dubai Marina behind glass, composed look.',
    bannerPrompt: 'Server racks with cable management too neat to be real.',
    postingStyle: 'Occasional dry-humour updates.',
    labInterests: ['fintech'],
    dmStyle: 'Replies with a checklist.',
    moderationRisk: 'normal',
    activity: 'low',
    testPurpose: 'Gulf-diaspora member; timezone spread; occasional-contributor pattern.',
  },
  {
    handle: 'zakariye_ml',
    displayName: 'Zakariye Axmed Samatar',
    ageBand: '18-24',
    locationCountry: 'US',
    locationCity: 'Columbus',
    timezone: 'America/New_York',
    languages: ['en'],
    preferredLanguage: 'en',
    lowBandwidth: false,
    oneLine: 'CS undergrad into machine learning; English-only.',
    bio: 'CS junior at Ohio State. Working on Somali ASR (speech recognition) for my capstone — ironically, I can barely speak Somali myself. Trying to fix that too.',
    skills: ['machine learning', 'python', 'research'],
    interests: ['ai', 'language-tech'],
    lanes: ['education', 'telecom'],
    openTo: ['hire_me', 'collaborating'],
    availability: 'Semester-dependent.',
    membershipTier: 'free',
    role: 'member',
    isVerifier: false,
    verification: 'unverified',
    accountStatus: 'active',
    completeness: 'partial',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Somali-American student, 20, campus hoodie, library backdrop, laptop covered in ML stickers.',
    bannerPrompt: 'Waveforms and Somali text overlaid, research-poster aesthetic.',
    postingStyle: 'English-only technical asks; shares papers.',
    labInterests: ['language-tech', 'education'],
    dmStyle: 'Formal at first, memes later.',
    moderationRisk: 'normal',
    activity: 'medium',
    testPurpose: 'Second-generation diaspora (English-only) — tests bilingual UX from the non-Somali-speaking side.',
  },
  {
    handle: 'faadumo_qa',
    displayName: 'Faadumo Cali Roble',
    ageBand: '25-34',
    locationCountry: 'FI',
    locationCity: 'Helsinki',
    timezone: 'Europe/Helsinki',
    languages: ['fi', 'en', 'so'],
    preferredLanguage: 'en',
    lowBandwidth: false,
    oneLine: 'QA engineer; finds the bug you shipped on Friday.',
    bio: null,
    skills: ['software development'],
    interests: ['testing'],
    lanes: ['professional-services'],
    openTo: [],
    availability: 'Unstated.',
    membershipTier: 'free',
    role: 'member',
    isVerifier: false,
    verification: 'unverified',
    accountStatus: 'active',
    completeness: 'minimal',
    hasAvatar: false,
    hasBanner: false,
    avatarPrompt: 'Somali-Finnish woman, 28, beanie, snow-lit window, deadpan expression.',
    bannerPrompt: 'A single red test-failure line in a sea of green.',
    postingStyle: 'Nearly silent; one dry comment per month.',
    labInterests: [],
    dmStyle: 'Emoji-only acknowledgements.',
    moderationRisk: 'normal',
    activity: 'lurker',
    testPurpose: 'Minimal profile (no bio, no avatar) in directory/search results.',
  },

  // ───────────────────────── agriculture / climate ─────────────────────────
  {
    handle: 'xasan_beero',
    displayName: 'Xasan Nuur Maxamed',
    ageBand: '45-54',
    locationCountry: 'SO',
    locationCity: 'Baidoa',
    timezone: 'Africa/Mogadishu',
    languages: ['so'],
    preferredLanguage: 'so',
    lowBandwidth: true,
    oneLine: 'Sorghum and sesame farmer near Baidoa.',
    bio: 'Beeraley reer Baydhabo ah. Waxaan beeraa masago iyo sisin. Waxaan raadinayaa macluumaad saabsan miraha abaaraha u adkaysta iyo suuqyo cusub. Qoraalka Ingiriisiga waan akhriyaa laakiin waxaan ku qoraa af Soomaali.',
    skills: ['agriculture'],
    interests: ['drought-resistant-crops', 'markets'],
    lanes: ['agri-food'],
    openTo: ['collaborating'],
    availability: 'Subax hore (early mornings).',
    membershipTier: 'free',
    role: 'member',
    isVerifier: false,
    verification: 'unverified',
    accountStatus: 'active',
    completeness: 'partial',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Somali farmer, 50, weathered kind face, light shawl, sorghum field at dawn.',
    bannerPrompt: 'Sorghum rows under a wide Bay-region sky.',
    postingStyle: 'Short Somali posts with practical farming questions.',
    labInterests: ['agri-food'],
    dmStyle: 'Voice-note-length single messages.',
    moderationRisk: 'normal',
    activity: 'medium',
    testPurpose: 'Somali-only + low-bandwidth + rural member; HITL Somali-language review lane; club member.',
  },
  {
    handle: 'amina_biyo',
    displayName: 'Aamina Ibraahim Waberi',
    ageBand: '35-44',
    locationCountry: 'SO',
    locationCity: 'Beledweyne',
    timezone: 'Africa/Mogadishu',
    languages: ['so', 'en'],
    preferredLanguage: 'so',
    lowBandwidth: false,
    oneLine: 'Irrigation and climate-adaptation worker on the Shabelle.',
    bio: 'Waxaan ka shaqeeyaa waraabka iyo la-qabsiga cimilada ee dooxada Shabeelle. NGO-yada iyo beeralayda ayaan isku xiraa. Leading the Beeraha iyo Biyaha club here — biyo la’aan, beero la’aan. Flood early-warning is my current obsession.',
    skills: ['agriculture', 'civil engineering', 'project management'],
    interests: ['irrigation', 'climate', 'early-warning'],
    lanes: ['agri-food', 'energy'],
    openTo: ['collaborating', 'mentoring'],
    availability: 'Field days vary; online most evenings.',
    membershipTier: 'supporter',
    role: 'member',
    isVerifier: false,
    verification: 'community_verified',
    accountStatus: 'active',
    completeness: 'full',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Somali woman, 39, sun hat over hijab, clipboard, river irrigation canal behind.',
    bannerPrompt: 'Shabelle river bend with green irrigated fields, aerial view.',
    postingStyle: 'Bilingual updates with field observations; organises the agri club.',
    labInterests: ['agri-food', 'climate'],
    dmStyle: 'Organiser energy: bullet points and deadlines.',
    moderationRisk: 'normal',
    activity: 'high',
    testPurpose: 'Club lead (club→lab ladder untriggered), Somali-first Supporter, climate/agriculture cluster hub.',
  },
  {
    handle: 'geedi_xoolo',
    displayName: 'Geedi Faarax Culusow',
    ageBand: '55-64',
    locationCountry: 'SO',
    locationCity: 'Garowe',
    timezone: 'Africa/Mogadishu',
    languages: ['so'],
    preferredLanguage: 'so',
    lowBandwidth: true,
    oneLine: 'Livestock trader, Garowe.',
    bio: 'Ganacsade xoolo ah oo Garoowe deggan. Riyo iyo ido. Wiilkaygaa ii sameeyay akoonkan.',
    skills: [],
    interests: ['livestock', 'export'],
    lanes: ['livestock'],
    openTo: [],
    availability: 'Suuqa subax kasta.',
    membershipTier: 'free',
    role: 'member',
    isVerifier: false,
    verification: 'unverified',
    accountStatus: 'active',
    completeness: 'minimal',
    hasAvatar: false,
    hasBanner: false,
    avatarPrompt: 'Somali elder trader, 60, prayer beads, livestock market, dignified.',
    bannerPrompt: 'Goats at a dusty Garowe market at sunrise.',
    postingStyle: 'Rare; one-line Somali questions about export prices.',
    labInterests: [],
    dmStyle: 'Prefers others to call him.',
    moderationRisk: 'normal',
    activity: 'low',
    testPurpose: 'Older, minimal-profile, Somali-only, low-bandwidth member — the accessibility floor.',
  },
  {
    handle: 'hamdi_agritech',
    displayName: 'Hamdi Yuusuf Cige',
    ageBand: '18-24',
    locationCountry: 'ET',
    locationCity: 'Jigjiga',
    timezone: 'Africa/Addis_Ababa',
    languages: ['so', 'en', 'am'],
    preferredLanguage: 'en',
    lowBandwidth: true,
    oneLine: 'Agronomy student bridging farms and apps.',
    bio: 'Agronomy student in Jigjiga (Somali Region, Ethiopia). I want to build tools farmers like my father would actually use — offline-first or nothing. Member of both the agri club and the fintech lab, translating between them.',
    skills: ['agriculture', 'data analysis', 'mobile development'],
    interests: ['agritech', 'offline-first', 'extension-services'],
    lanes: ['agri-food', 'fintech'],
    openTo: ['collaborating', 'hire_me'],
    availability: 'Evenings EAT.',
    membershipTier: 'free',
    role: 'member',
    isVerifier: false,
    verification: 'unverified',
    accountStatus: 'active',
    completeness: 'full',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Young Somali woman, 22, field notebook, experimental crop plots, bright morning.',
    bannerPrompt: 'Split image: maize field and a phone screen with a farming app.',
    postingStyle: 'Cross-posts between agri and tech; asks bridging questions.',
    labInterests: ['agri-food', 'fintech'],
    dmStyle: 'Curious, quick, bilingual.',
    moderationRisk: 'normal',
    activity: 'medium',
    testPurpose: 'Ethiopia-based Somali (region diversity beyond SO), cross-cluster bridge, offline-first tester.',
  },
  {
    handle: 'kalluun_kismayo',
    displayName: 'Maxamed Cabdullaahi Xirsi',
    ageBand: '35-44',
    locationCountry: 'SO',
    locationCity: 'Kismayo',
    timezone: 'Africa/Mogadishu',
    languages: ['so'],
    preferredLanguage: 'so',
    lowBandwidth: true,
    oneLine: 'Fisherman and fishing co-op member, Kismayo.',
    bio: 'Kalluumeysato reer Kismaayo ah. Waxaan ka mid ahay iskaashatada kalluumeysiga. Qaboojiye la’aanta ayaa naga dhibaysa — kalluunka waa qurbo haddii aan la gaadhin suuqa saacado gudahood.',
    skills: [],
    interests: ['fishing', 'cold-chain'],
    lanes: ['fishing'],
    openTo: ['collaborating'],
    availability: 'Habeenkii dambe (late evenings).',
    membershipTier: 'free',
    role: 'member',
    isVerifier: false,
    verification: 'unverified',
    accountStatus: 'active',
    completeness: 'partial',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Somali fisherman, 40, salt-faded cap, harbour nets behind, honest tired smile.',
    bannerPrompt: 'Kismayo harbour with small fishing boats at dusk.',
    postingStyle: 'Occasional Somali asks about cold-chain and prices.',
    labInterests: ['fishing'],
    dmStyle: 'Short and practical.',
    moderationRisk: 'normal',
    activity: 'low',
    testPurpose: 'Coastal-economy persona; Somali-only ask that the AI helper answers.',
  },
  {
    handle: 'ubax_beerta',
    displayName: 'Ubax Xasan Dhuxul',
    ageBand: '25-34',
    locationCountry: 'SO',
    locationCity: 'Borama',
    timezone: 'Africa/Mogadishu',
    languages: ['so', 'en'],
    preferredLanguage: 'so',
    lowBandwidth: false,
    oneLine: 'Greenhouse grower in Borama; tomatoes with opinions.',
    bio: 'Greenhouse-ka Boorama: yaanyo, barbarooni, iyo khudaar caleen ah. Waxaan tijaabinayaa biyo-yarayn (drip irrigation). Wixii aad rabto inaad ka ogaato beerashada daaqadaha — weydii! I sell to hotels in Hargeisa on weekends.',
    skills: ['agriculture', 'sales'],
    interests: ['greenhouse', 'drip-irrigation', 'horticulture'],
    lanes: ['agri-food', 'retail'],
    openTo: ['collaborating'],
    availability: 'Daily, early morning.',
    membershipTier: 'free',
    role: 'member',
    isVerifier: false,
    verification: 'unverified',
    accountStatus: 'active',
    completeness: 'full',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Somali woman, 27, inside a greenhouse, tomato vines, joyful.',
    bannerPrompt: 'Rows of greenhouse tomatoes with drip lines glinting.',
    postingStyle: 'Cheerful Somali wins about harvests; answers growing questions.',
    labInterests: ['agri-food'],
    dmStyle: 'Friendly, sends prices fast.',
    moderationRisk: 'needs_review',
    activity: 'medium',
    testPurpose: 'Somali content routed to the HITL uncertain queue (approved case); female agripreneur.',
  },

  // ───────────────────────── women's co-op / craft ─────────────────────────
  {
    handle: 'khadra_coop',
    displayName: 'Khadra Aadan Geeddi',
    ageBand: '45-54',
    locationCountry: 'SO',
    locationCity: 'Hargeisa',
    timezone: 'Africa/Mogadishu',
    languages: ['so', 'en'],
    preferredLanguage: 'so',
    lowBandwidth: false,
    oneLine: 'Chairwoman of a 40-member women’s savings co-op.',
    bio: 'Guddoomiyaha iskaashato haween ah oo 40 xubnood leh — hagbad, tababar, iyo ganacsi yaryar. 15 sano ayaan hawshan ku jiray. Waxaan halkan u joogaa inaan xubnaha ku xiro suuqyo iyo aqoon cusub. Leading the Iskaashato Hooyo Lab on Xidig.',
    skills: ['fundraising', 'leadership', 'bookkeeping'],
    interests: ['savings-groups', 'women-in-business', 'microfinance'],
    lanes: ['halal-finance', 'nonprofit'],
    openTo: ['mentoring', 'collaborating'],
    availability: 'Afternoons.',
    membershipTier: 'supporter',
    role: 'member',
    isVerifier: false,
    verification: 'community_verified',
    accountStatus: 'active',
    completeness: 'full',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Somali woman, 50, elegant guntiino, market office, commanding warmth.',
    bannerPrompt: 'Women’s co-op meeting circle with ledger books and tea.',
    postingStyle: 'Somali-first organisational updates; celebrates member milestones.',
    labInterests: ['halal-finance', 'women-in-business'],
    dmStyle: 'Matriarch: brief, decisive, kind.',
    moderationRisk: 'normal',
    activity: 'high',
    testPurpose: 'Second Lab lead (promoted club→lab), Supporter, community-verified via vouches, co-op cluster hub.',
  },
  {
    handle: 'hibo_dhar',
    displayName: 'Hibo Maxamed Nuux',
    ageBand: '35-44',
    locationCountry: 'SO',
    locationCity: 'Mogadishu',
    timezone: 'Africa/Mogadishu',
    languages: ['so'],
    preferredLanguage: 'so',
    lowBandwidth: true,
    oneLine: 'Tailor; school uniforms and wedding dirac.',
    bio: 'Dawaarle. Waxaan tolaa dirac, guntiino iyo lebbiska dugsiyada. Amarka waan qaabilaa WhatsApp — halkan waxaan ka raadinayaa macaamiil cusub.',
    skills: ['tailoring'],
    interests: ['fashion', 'weddings'],
    lanes: ['fashion'],
    openTo: ['hire_me'],
    availability: 'Sabti ilaa Khamiis.',
    membershipTier: 'free',
    role: 'member',
    isVerifier: false,
    verification: 'unverified',
    accountStatus: 'active',
    completeness: 'partial',
    hasAvatar: true,
    hasBanner: false,
    avatarPrompt: 'Somali seamstress, 38, measuring tape around neck, colourful fabric bolts behind.',
    bannerPrompt: 'Rows of dirac fabric in jewel tones.',
    postingStyle: 'Rare Somali posts showing finished work.',
    labInterests: ['fashion'],
    dmStyle: 'Replies with prices and delivery days.',
    moderationRisk: 'normal',
    activity: 'low',
    testPurpose: 'Informal-economy member, Somali-only, co-op lab membership, no-avatar rendering.',
  },
  {
    handle: 'sahra_xinne',
    displayName: 'Sahra Cumar Bootaan',
    ageBand: '18-24',
    locationCountry: 'SO',
    locationCity: 'Hargeisa',
    timezone: 'Africa/Mogadishu',
    languages: ['so', 'en'],
    preferredLanguage: 'so',
    lowBandwidth: false,
    oneLine: 'Henna artist booking Eid slots.',
    bio: 'Xinne iyo farshaxan. Booking-ka Ciidda wuu furan yahay!',
    skills: ['graphic design'],
    interests: ['henna', 'weddings', 'art'],
    lanes: ['creative-arts', 'fashion'],
    openTo: ['hire_me'],
    availability: 'Galabnimo.',
    membershipTier: 'free',
    role: 'member',
    isVerifier: false,
    verification: 'unverified',
    accountStatus: 'active',
    completeness: 'minimal',
    hasAvatar: true,
    hasBanner: false,
    avatarPrompt: 'Young Somali woman, 20, showing hennaed hands crossed under chin, studio light.',
    bannerPrompt: 'Intricate henna patterns close-up, warm amber tones.',
    postingStyle: 'Short Somali promos with emoji.',
    labInterests: [],
    dmStyle: 'Fast, emoji-heavy.',
    moderationRisk: 'normal',
    activity: 'low',
    testPurpose: 'Young micro-entrepreneur; minimal profile with avatar but no bio depth.',
  },
  {
    handle: 'muna_macaan',
    displayName: 'Muna Siciid Careys',
    ageBand: '25-34',
    locationCountry: 'KE',
    locationCity: 'Nairobi',
    timezone: 'Africa/Nairobi',
    languages: ['so', 'en', 'sw'],
    preferredLanguage: 'en',
    lowBandwidth: false,
    oneLine: 'Runs Macaan Bakery in Eastleigh; halwa that sells out by noon.',
    bio: 'Founder of Macaan Bakery, Eastleigh. Somali sweets — halwa, buskut, kac kac — plus birthday cakes. Started from my kitchen in 2023, now three staff. Dreaming about a second branch and terrified about it too. Xidig listing below!',
    skills: ['sales', 'marketing', 'bookkeeping'],
    interests: ['food', 'small-business', 'franchising'],
    lanes: ['agri-food', 'retail', 'hospitality'],
    openTo: ['hiring', 'collaborating'],
    availability: 'After 3pm EAT.',
    membershipTier: 'free',
    role: 'member',
    isVerifier: false,
    verification: 'unverified',
    accountStatus: 'active',
    completeness: 'full',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Somali-Kenyan woman, 29, apron over abaya, bakery counter with halwa trays, proud grin.',
    bannerPrompt: 'Golden halwa and kac kac arranged on brass trays.',
    postingStyle: 'Wins about sales milestones; asks about scaling.',
    labInterests: ['women-in-business'],
    dmStyle: 'Warm, businesslike, sends menus.',
    moderationRisk: 'normal',
    activity: 'medium',
    testPurpose: 'Member-owned business listing; win posts; co-op lab member; listing search.',
  },
  {
    handle: 'fartuun_forsa',
    displayName: 'Fartuun Daahir Weheliye',
    ageBand: '35-44',
    locationCountry: 'GB',
    locationCity: 'Cardiff',
    timezone: 'Europe/London',
    languages: ['en', 'so'],
    preferredLanguage: 'en',
    lowBandwidth: false,
    oneLine: 'Business mentor pairing diaspora skills with home-country co-ops.',
    bio: 'Cardiff-based, Burco-born. I spent a decade in UK retail banking; now I mentor women-led co-ops on bookkeeping and pricing. Mentorship is sadaqah with compound interest. Supporter here because the mission deserves £1.',
    skills: ['finance', 'consulting', 'bookkeeping', 'public speaking'],
    interests: ['microfinance', 'mentorship', 'women-in-business'],
    lanes: ['halal-finance', 'professional-services'],
    openTo: ['mentoring'],
    availability: 'Tuesday + Thursday evenings.',
    membershipTier: 'supporter',
    role: 'member',
    isVerifier: false,
    verification: 'unverified',
    accountStatus: 'active',
    completeness: 'full',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Somali-Welsh woman, 41, smart casual, Cardiff bay window light, encouraging expression.',
    bannerPrompt: 'A ledger, a calculator and a cup of shaah on a wooden desk.',
    postingStyle: 'Thoughtful advice comments; monthly “office hours” update.',
    labInterests: ['halal-finance'],
    dmStyle: 'Structured mentor replies with action items.',
    moderationRisk: 'normal',
    activity: 'medium',
    testPurpose: 'Diaspora↔home mentorship bridge; Supporter without a lab lead role; endorsement source.',
  },

  // ───────────────────────── diaspora business / investment ─────────────────
  {
    handle: 'abshir_maal',
    displayName: 'Abshir Warfaa Iidle',
    ageBand: '45-54',
    locationCountry: 'US',
    locationCity: 'Minneapolis',
    timezone: 'America/Chicago',
    languages: ['en', 'so'],
    preferredLanguage: 'en',
    lowBandwidth: false,
    oneLine: 'Diaspora investor; three restaurants and a patient chequebook.',
    bio: 'Minneapolis. Built three halal restaurants over 20 years; now I back Somali founders with small cheques and blunt advice. I read every candidate on this platform. Note: I invest from the US, so the Maalgeli door stays politely closed to me — as it should.',
    skills: ['business development', 'finance', 'consulting'],
    interests: ['investing', 'restaurants', 'venture'],
    lanes: ['hospitality', 'halal-finance'],
    openTo: ['investing', 'mentoring'],
    availability: 'By appointment.',
    membershipTier: 'supporter',
    role: 'member',
    isVerifier: false,
    verification: 'identity_verified',
    accountStatus: 'active',
    completeness: 'full',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Somali-American man, 52, salt-and-pepper beard, blazer no tie, restaurant interior, assured.',
    bannerPrompt: 'A busy halal restaurant pass with plated bariis and hilib ari.',
    postingStyle: 'Measured, numbers-first comments on candidates and business asks.',
    labInterests: ['investing'],
    dmStyle: 'Direct questions about margins.',
    moderationRisk: 'normal',
    activity: 'medium',
    testPurpose: 'Region-gate DENIED case (US profile country → Maalgeli blocked, gate evaluation logged); supporter votes; investor persona.',
  },
  {
    handle: 'deeqa_dirham',
    displayName: 'Deeqa Aweys Guuleed',
    ageBand: '35-44',
    locationCountry: 'AE',
    locationCity: 'Dubai',
    timezone: 'Asia/Dubai',
    languages: ['so', 'en', 'ar'],
    preferredLanguage: 'en',
    lowBandwidth: false,
    oneLine: 'Import/export between Dubai, Berbera and Mogadishu.',
    bio: 'Trader. Electronics and household goods out of Dragon Mart; sesame and hides on the return leg. Twelve years, three ports, one rule: paperwork before promises. Verified business on Xidig — check the badge, then let’s talk.',
    skills: ['business development', 'logistics', 'sales'],
    interests: ['trade', 'shipping', 'customs'],
    lanes: ['import-export', 'logistics'],
    openTo: ['collaborating', 'hiring'],
    availability: 'GST working hours.',
    membershipTier: 'supporter',
    role: 'member',
    isVerifier: false,
    verification: 'identity_verified',
    accountStatus: 'active',
    completeness: 'full',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Somali businesswoman, 40, dark abaya with sharp tailoring, container-port backdrop, formidable.',
    bannerPrompt: 'Stacked shipping containers with a Dubai crane skyline.',
    postingStyle: 'Trade-lane updates, customs tips, no-nonsense answers.',
    labInterests: ['import-export'],
    dmStyle: 'Fast, transactional, exact.',
    moderationRisk: 'normal',
    activity: 'medium',
    testPurpose: 'Verified BUSINESS (listing-level verification + badge), supporter-only space member, trade cluster hub.',
  },
  {
    handle: 'yusuf_xawilaad',
    displayName: 'Yuusuf Cabdiraxmaan Sheekh',
    ageBand: '55-64',
    locationCountry: 'GB',
    locationCity: 'London',
    timezone: 'Europe/London',
    languages: ['so', 'en'],
    preferredLanguage: 'so',
    lowBandwidth: false,
    oneLine: 'Thirty years behind a xawilaad counter in Whitechapel.',
    bio: 'Xawilaad agent since 1994. I have sent other people’s money home through three currency collapses, two banking crackdowns, and one fax machine. The young engineers building “remittance disruption” apps are welcome to my counter for a day — you will learn more than in ten pitch decks. Waxaan aaminsanahay in lacagtu tahay aamin, mana aha software oo keliya. Long bios are for people with long stories; I have earned mine.',
    skills: ['finance', 'accounting'],
    interests: ['remittance', 'regulation', 'history'],
    lanes: ['remittance', 'halal-finance'],
    openTo: ['mentoring'],
    availability: 'Shop hours; ask for Yuusuf.',
    membershipTier: 'free',
    role: 'member',
    isVerifier: false,
    verification: 'community_verified',
    accountStatus: 'active',
    completeness: 'full',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Somali elder, 58, reading glasses on forehead, xawilaad counter with ledgers, wry knowing look.',
    bannerPrompt: 'A worn remittance-shop counter with currency boards and handwritten rates.',
    postingStyle: 'Long, story-driven comments that end with one sharp question.',
    labInterests: ['fintech'],
    dmStyle: 'Prefers long-form; types slowly, thinks fast.',
    moderationRisk: 'normal',
    activity: 'medium',
    testPurpose: 'Long-bio rendering, elder domain expert vs young builders dynamic, Somali-preferring UK member.',
  },
  {
    handle: 'ifrah_invest',
    displayName: 'Ifraax Maxamed Gaas',
    ageBand: '25-34',
    locationCountry: 'SO',
    locationCity: 'Mogadishu',
    timezone: 'Africa/Mogadishu',
    languages: ['so', 'en'],
    preferredLanguage: 'en',
    lowBandwidth: false,
    oneLine: 'Returnee angel; moved back from Nairobi to invest at home.',
    bio: 'Moved back to Mogadishu in 2024 after eight years in Nairobi banking. I invest small amounts in Somali ventures and document the journey honestly — the wins and the wire-transfer headaches. Attested, verified, and Maalgeli-ready. Building the investor circle here.',
    skills: ['finance', 'business development', 'data analysis'],
    interests: ['investing', 'venture', 'returnee-life'],
    lanes: ['halal-finance', 'fintech'],
    openTo: ['investing', 'cofounding'],
    availability: 'Most days.',
    membershipTier: 'supporter',
    role: 'member',
    isVerifier: false,
    verification: 'identity_verified',
    accountStatus: 'active',
    completeness: 'full',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Somali woman, 31, tailored blazer over hijab, Mogadishu rooftop café, optimistic.',
    bannerPrompt: 'Mogadishu Lido beach boardwalk at golden hour.',
    postingStyle: 'Transparent investing updates; asks founders hard, fair questions.',
    labInterests: ['investing', 'fintech'],
    dmStyle: 'Crisp, numbers plus encouragement.',
    moderationRisk: 'normal',
    activity: 'high',
    testPurpose: 'Region-gate GRANTED case (SO + attested → Maalgeli invest intent logged); identity verification; supporter governance votes.',
  },
  {
    handle: 'tahliil_textile',
    displayName: 'Tahliil Xuseen Cawil',
    ageBand: '35-44',
    locationCountry: 'TR',
    locationCity: 'Istanbul',
    timezone: 'Europe/Istanbul',
    languages: ['so', 'tr', 'en'],
    preferredLanguage: 'so',
    lowBandwidth: false,
    oneLine: 'Textile wholesaler in Istanbul’s Fatih district.',
    bio: 'Dharka jumlada — Istanbul ilaa Muqdisho iyo Hargeysa. Waxaan xidhiidhiyaa warshadaha Turkiga iyo ganacsatada Soomaaliyeed.',
    skills: ['sales', 'logistics'],
    interests: ['textiles', 'wholesale'],
    lanes: ['import-export', 'fashion'],
    openTo: ['collaborating'],
    availability: 'TRT daytime.',
    membershipTier: 'free',
    role: 'member',
    isVerifier: false,
    verification: 'unverified',
    accountStatus: 'active',
    completeness: 'partial',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Somali man, 37, wool coat, Istanbul fabric bazaar corridor, streetwise calm.',
    bannerPrompt: 'Bolts of fabric stacked to the ceiling in a Fatih warehouse.',
    postingStyle: 'Occasional Somali trade offers and price updates.',
    labInterests: ['import-export'],
    dmStyle: 'Deal-focused; switches to voice calls quickly.',
    moderationRisk: 'normal',
    activity: 'low',
    testPurpose: 'Turkey-diaspora node; trilingual member; partial profile with avatar.',
  },
  {
    handle: 'asli_cijaar',
    displayName: 'Asli Nuur Qaasim',
    ageBand: '25-34',
    locationCountry: 'NL',
    locationCity: 'Amsterdam',
    timezone: 'Europe/Amsterdam',
    languages: ['nl', 'en', 'so'],
    preferredLanguage: 'en',
    lowBandwidth: false,
    oneLine: 'Chartered accountant; makes VAT almost interesting.',
    bio: 'Accountant at a Big-4 firm in Amsterdam. I help Somali businesses in NL with their books pro bono one Saturday a month. Complete profile, quiet presence — I mostly read and endorse people who deserve it.',
    skills: ['accounting', 'finance', 'consulting'],
    interests: ['tax', 'small-business'],
    lanes: ['professional-services', 'halal-finance'],
    openTo: ['collaborating'],
    availability: 'First Saturday monthly.',
    membershipTier: 'free',
    role: 'member',
    isVerifier: false,
    verification: 'unverified',
    accountStatus: 'active',
    completeness: 'full',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Somali-Dutch woman, 30, minimal jewellery, canal-house office, composed.',
    bannerPrompt: 'Amsterdam canal reflections in autumn.',
    postingStyle: 'Rare, precise tax-question answers.',
    labInterests: [],
    dmStyle: 'Formal, schedules everything.',
    moderationRisk: 'normal',
    activity: 'lurker',
    testPurpose: 'Full profile + lurker activity mismatch (directory-strong, feed-quiet); endorsements source.',
  },

  // ───────────────────────── health ─────────────────────────
  {
    handle: 'maryan_kalkaal',
    displayName: 'Maryan Aadan Maxamed',
    ageBand: '25-34',
    locationCountry: 'SO',
    locationCity: 'Mogadishu',
    timezone: 'Africa/Mogadishu',
    languages: ['so', 'en'],
    preferredLanguage: 'so',
    lowBandwidth: false,
    oneLine: 'Maternity nurse at Banadir Hospital; answers health questions patiently.',
    bio: 'Kalkaaliso umulisa ah, cisbitaalka Banaadir. Waxaan halkan ugu jawaabaa su’aalaha caafimaadka hooyada iyo dhallaanka — talo guud, ma aha baaritaan. Fadlan dhakhtar u tag xaaladaha degdegga ah. Nurse first, health educator second, tired always.',
    skills: ['nursing', 'medicine', 'teaching'],
    interests: ['maternal-health', 'public-health', 'health-education'],
    lanes: ['health'],
    openTo: ['mentoring'],
    availability: 'Off-shift evenings.',
    membershipTier: 'supporter',
    role: 'member',
    isVerifier: false,
    verification: 'community_verified',
    accountStatus: 'active',
    completeness: 'full',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Somali nurse, 32, white hijab and scrubs, hospital corridor, compassionate steady gaze.',
    bannerPrompt: 'Sunrise over Banadir Hospital entrance, hopeful tone.',
    postingStyle: 'Patient Somali health explainers; most-credited answerer.',
    labInterests: ['health'],
    dmStyle: 'Kind, firm boundaries about medical advice.',
    moderationRisk: 'normal',
    activity: 'high',
    testPurpose: 'Top helper reputation, credited answers, community-verified via vouches, pending identity verification (scheduled).',
  },
  {
    handle: 'cabdi_daawo',
    displayName: 'Cabdi Faarax Maxamuud',
    ageBand: '35-44',
    locationCountry: 'SO',
    locationCity: 'Hargeisa',
    timezone: 'Africa/Mogadishu',
    languages: ['so', 'en'],
    preferredLanguage: 'so',
    lowBandwidth: false,
    oneLine: 'Pharmacist; fights counterfeit medicine one batch at a time.',
    bio: 'Farmashiyaha guud ee Hargeysa. Waxaan ka digaa daawooyinka been-abuurka ah — barcode-ka hubi, taariikhda hubi. Su’aalo daawo? Waan jawaabayaa markaan xarunta ka baxo.',
    skills: ['pharmacy', 'medicine'],
    interests: ['pharma-supply-chain', 'counterfeit-detection'],
    lanes: ['health', 'retail'],
    openTo: ['collaborating'],
    availability: 'Evenings.',
    membershipTier: 'free',
    role: 'member',
    isVerifier: false,
    verification: 'unverified',
    accountStatus: 'active',
    completeness: 'partial',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Somali pharmacist, 39, white coat, shelves of medicine boxes, meticulous air.',
    bannerPrompt: 'Pharmacy shelves in orderly rows, clinical light.',
    postingStyle: 'Short Somali safety warnings about medicines.',
    labInterests: ['health'],
    dmStyle: 'Careful, checks before answering.',
    moderationRisk: 'normal',
    activity: 'low',
    testPurpose: 'Health-cluster supporting member; safety-content patterns.',
  },
  {
    handle: 'nimco_caafimaad',
    displayName: 'Nimco Cali Dhoore',
    ageBand: '45-54',
    locationCountry: 'SO',
    locationCity: 'Kismayo',
    timezone: 'Africa/Mogadishu',
    languages: ['so'],
    preferredLanguage: 'so',
    lowBandwidth: true,
    oneLine: 'Community health worker walking district to district.',
    bio: 'Shaqaale caafimaadka bulshada. Tallaalka, nafaqada, iyo hooyooyinka uurka leh ayaan la socdaa degmooyinka Kismaayo. Telefoonkaygu waa mid duug ah, internet-kuna waa gabow — ha ii soo dirin sawiro waaweyn fadlan.',
    skills: ['nursing', 'teaching'],
    interests: ['vaccination', 'nutrition'],
    lanes: ['health', 'nonprofit'],
    openTo: [],
    availability: 'Habeenkii oo keliya.',
    membershipTier: 'free',
    role: 'member',
    isVerifier: false,
    verification: 'unverified',
    accountStatus: 'active',
    completeness: 'partial',
    hasAvatar: true,
    hasBanner: false,
    avatarPrompt: 'Somali health worker, 48, sun-shielding garbasaar, clinic doorway, resilient warmth.',
    bannerPrompt: 'A dusty road between villages with a medical bag in the foreground.',
    postingStyle: 'Rare Somali updates from the field.',
    labInterests: [],
    dmStyle: 'Slow replies, old phone.',
    moderationRisk: 'normal',
    activity: 'low',
    testPurpose: 'Low-bandwidth + old-device persona; Somali-only; frontline health voice.',
  },
  {
    handle: 'axmed_caafi',
    displayName: 'Axmed Saleebaan Nuur',
    ageBand: '25-34',
    locationCountry: 'NO',
    locationCity: 'Oslo',
    timezone: 'Europe/Oslo',
    languages: ['no', 'en', 'so'],
    preferredLanguage: 'en',
    lowBandwidth: false,
    oneLine: 'Final-year medical student in Oslo.',
    bio: null,
    skills: ['medicine', 'research'],
    interests: ['cardiology', 'diaspora-health'],
    lanes: ['health'],
    openTo: ['collaborating'],
    availability: 'Exam-season dependent.',
    membershipTier: 'free',
    role: 'member',
    isVerifier: false,
    verification: 'unverified',
    accountStatus: 'active',
    completeness: 'minimal',
    hasAvatar: true,
    hasBanner: false,
    avatarPrompt: 'Somali-Norwegian medical student, 26, stethoscope, hospital library, focused.',
    bannerPrompt: 'Oslo fjord in blue hour.',
    postingStyle: 'Rare study-related comments.',
    labInterests: ['health'],
    dmStyle: 'Polite, brief.',
    moderationRisk: 'normal',
    activity: 'lurker',
    testPurpose: 'Minimal profile (no bio/avatar), Nordic diaspora, quiet member.',
  },

  // ───────────────────────── education ─────────────────────────
  {
    handle: 'cali_macalin',
    displayName: 'Cali Xasan Cabdulle',
    ageBand: '45-54',
    locationCountry: 'SO',
    locationCity: 'Baidoa',
    timezone: 'Africa/Mogadishu',
    languages: ['so', 'en', 'ar'],
    preferredLanguage: 'so',
    lowBandwidth: true,
    oneLine: 'Secondary-school maths teacher for 22 years.',
    bio: 'Macalin xisaabeed, dugsiga sare ee Baydhabo. 22 sano. Waxaan aaminsanahay in xisaabtu tahay luuqadda kowaad ee horumarka. Waxaan raadinayaa buugaag iyo qalab casri ah oo ardaydaydu ku bartaan — internet la’aan ayaa nagu adag. Marka aan qorayo halkan, waxaan u qorayaa ardaydayda mustaqbalka.',
    skills: ['teaching', 'tutoring'],
    interests: ['maths-education', 'teacher-training', 'offline-learning'],
    lanes: ['education'],
    openTo: ['mentoring', 'collaborating'],
    availability: 'After school hours.',
    membershipTier: 'free',
    role: 'member',
    isVerifier: false,
    verification: 'community_verified',
    accountStatus: 'active',
    completeness: 'full',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Somali teacher, 49, chalk dust on sleeve, blackboard with equations, gentle authority.',
    bannerPrompt: 'A classroom blackboard full of neat mathematics in chalk.',
    postingStyle: 'Reflective Somali essays about education; asks for resources.',
    labInterests: ['education'],
    dmStyle: 'Letters, not messages.',
    moderationRisk: 'normal',
    activity: 'medium',
    testPurpose: 'Teacher persona; education club member; long Somali text rendering; low-bandwidth.',
  },
  {
    handle: 'hafsa_dugsi',
    displayName: 'Xafsa Maxamed Saciid',
    ageBand: '18-24',
    locationCountry: 'SO',
    locationCity: 'Mogadishu',
    timezone: 'Africa/Mogadishu',
    languages: ['so', 'en'],
    preferredLanguage: 'en',
    lowBandwidth: false,
    oneLine: 'Economics undergrad; organises the campus study circle.',
    bio: 'Econ student at SNU. I run a 30-person study circle and I am unreasonably passionate about study techniques, group accountability, and iced coffee. Polls are my love language.',
    skills: ['research', 'public speaking', 'social media'],
    interests: ['economics', 'study-groups', 'youth'],
    lanes: ['education'],
    openTo: ['collaborating', 'hire_me'],
    availability: 'Between lectures.',
    membershipTier: 'free',
    role: 'member',
    isVerifier: false,
    verification: 'unverified',
    accountStatus: 'active',
    completeness: 'full',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Somali student, 21, bright hijab, campus courtyard, animated mid-laugh.',
    bannerPrompt: 'Study-circle whiteboard with colour-coded notes and sticky arrows.',
    postingStyle: 'Energetic polls and study-tip threads; emoji-fluent.',
    labInterests: ['education'],
    dmStyle: 'Rapid-fire, friendly.',
    moderationRisk: 'normal',
    activity: 'high',
    testPurpose: 'Poll creation + voting flows; young high-energy user; education club member.',
  },
  {
    handle: 'arday_hargeisa',
    displayName: 'Maxamed Deeq Yuusuf',
    ageBand: '18-24',
    locationCountry: 'SO',
    locationCity: 'Hargeisa',
    timezone: 'Africa/Mogadishu',
    languages: ['so'],
    preferredLanguage: 'so',
    lowBandwidth: true,
    oneLine: 'Student. New here.',
    bio: null,
    skills: [],
    interests: [],
    lanes: [],
    openTo: [],
    availability: 'Unknown.',
    membershipTier: 'free',
    role: 'member',
    isVerifier: false,
    verification: 'unverified',
    accountStatus: 'active',
    completeness: 'bare',
    hasAvatar: false,
    hasBanner: false,
    avatarPrompt: 'Somali teenager, 18, school shirt, shy half-smile, plain wall.',
    bannerPrompt: 'None.',
    postingStyle: 'None yet.',
    labInterests: [],
    dmStyle: 'Read receipts only.',
    moderationRisk: 'normal',
    activity: 'none',
    testPurpose: 'Bare profile (no lanes → incomplete): onboarding prompts, empty-profile rendering, directory edge case.',
  },
  {
    handle: 'zamzam_dugsiga',
    displayName: 'Zamzam Cabdi Nuur',
    ageBand: '55-64',
    locationCountry: 'CA',
    locationCity: 'Toronto',
    timezone: 'America/Toronto',
    languages: ['so', 'en', 'ar'],
    preferredLanguage: 'so',
    lowBandwidth: false,
    oneLine: 'Weekend dugsi coordinator and grandmother of six.',
    bio: 'Waxaan maamushaa dugsiga Sabtida iyo Axadda ee xarunta Islaamiga ee Toronto — 120 carruur ah. Ayeeyo lix carruur ah. Waxaan raadinayaa macalimiin mutadawiciin ah iyo hab lagu baro carruurta af Soomaaliga qurbaha.',
    skills: ['teaching', 'leadership'],
    interests: ['islamic-education', 'somali-language', 'volunteering'],
    lanes: ['education', 'nonprofit'],
    openTo: ['collaborating'],
    availability: 'Weekends at the centre.',
    membershipTier: 'free',
    role: 'member',
    isVerifier: false,
    verification: 'unverified',
    accountStatus: 'active',
    completeness: 'partial',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Somali grandmother, 58, dignified jilbaab, community-centre classroom, gentle strength.',
    bannerPrompt: 'Children’s Somali alphabet posters on a classroom wall.',
    postingStyle: 'Somali asks about curriculum and volunteers.',
    labInterests: ['education'],
    dmStyle: 'Warm, prays for you, then asks you to volunteer.',
    moderationRisk: 'normal',
    activity: 'medium',
    testPurpose: 'Older diaspora caregiver; volunteer recruitment ask; Somali-language-preservation thread.',
  },
  {
    handle: 'bashiir_baro',
    displayName: 'Bashiir Cali Guray',
    ageBand: '25-34',
    locationCountry: 'AU',
    locationCity: 'Melbourne',
    timezone: 'Australia/Melbourne',
    languages: ['en', 'so'],
    preferredLanguage: 'en',
    lowBandwidth: false,
    oneLine: 'Founder of a micro e-learning startup for Somali learners.',
    bio: 'Melbourne-based founder building Barasho — bite-size video lessons in Somali (maths and literacy first). Two-person team, 4,000 learners, zero funding, infinite stubbornness. Running our education club here in the open.',
    skills: ['product management', 'teaching', 'video editing', 'marketing'],
    interests: ['edtech', 'somali-language', 'video-learning'],
    lanes: ['education', 'media'],
    openTo: ['cofounding', 'hiring', 'collaborating'],
    availability: 'AEST evenings (your morning).',
    membershipTier: 'supporter',
    role: 'member',
    isVerifier: false,
    verification: 'unverified',
    accountStatus: 'active',
    completeness: 'full',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Somali-Australian man, 30, casual shirt, ring-light home studio, energetic.',
    bannerPrompt: 'Phone filming a whiteboard maths lesson, production-in-progress feel.',
    postingStyle: 'Build-in-public metrics posts; asks for beta testers.',
    labInterests: ['education', 'media'],
    dmStyle: 'Fast, link-heavy, timezone-apologetic.',
    moderationRisk: 'normal',
    activity: 'high',
    testPurpose: 'Private club lead (education), far-timezone member, founder persona, candidate pipeline (draft).',
  },

  // ───────────────────────── trades / logistics / shops ─────────────────────
  {
    handle: 'saciid_makaanik',
    displayName: 'Saciid Ibraahim Ducaale',
    ageBand: '35-44',
    locationCountry: 'SO',
    locationCity: 'Mogadishu',
    timezone: 'Africa/Mogadishu',
    languages: ['so'],
    preferredLanguage: 'so',
    lowBandwidth: true,
    oneLine: 'Mechanic; keeps Bakara’s minibuses alive.',
    bio: 'Makaanik gawaarida yaryar iyo bajaajta. Garaashkaygu wuxuu ku yaal agagaarka Bakaaraha. Qalab jaban? Ii keen, waan eegi.',
    skills: ['driving', 'welding'],
    interests: ['vehicles', 'spare-parts'],
    lanes: ['transport'],
    openTo: ['hire_me'],
    availability: 'Maalin kasta ilaa casarka.',
    membershipTier: 'free',
    role: 'member',
    isVerifier: false,
    verification: 'unverified',
    accountStatus: 'active',
    completeness: 'partial',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Somali mechanic, 38, oil-marked overalls, engine bay open behind, capable grin.',
    bannerPrompt: 'A garage courtyard with a bajaaj mid-repair.',
    postingStyle: 'Rare; answers vehicle questions in Somali.',
    labInterests: [],
    dmStyle: 'Sends prices, then “soo dhawow”.',
    moderationRisk: 'normal',
    activity: 'low',
    testPurpose: 'Claims the unclaimed demo garage listing (listing-claim flow); trades persona.',
  },
  {
    handle: 'faarax_gaadiid',
    displayName: 'Faarax Cumar Silaanyo',
    ageBand: '25-34',
    locationCountry: 'DJ',
    locationCity: 'Djibouti City',
    timezone: 'Africa/Djibouti',
    languages: ['so', 'fr', 'ar'],
    preferredLanguage: 'so',
    lowBandwidth: true,
    oneLine: 'Long-haul driver on the Djibouti–Addis corridor.',
    bio: 'Darawal xamuul — Jabuuti ilaa Addis, toddobaad kasta laba jeer. Waxaan ogahay meesha uu baabuurku ku jabayo iyo meesha shaahu ku macaan yahay. Wallo GPS-ka iga weydii.',
    skills: ['driving', 'logistics'],
    interests: ['trucking', 'border-crossings'],
    lanes: ['transport', 'logistics'],
    openTo: ['hire_me'],
    availability: 'Between hauls.',
    membershipTier: 'free',
    role: 'member',
    isVerifier: false,
    verification: 'unverified',
    accountStatus: 'active',
    completeness: 'partial',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Somali truck driver, 29, keffiyeh against dust, truck cab, road-worn cheerfulness.',
    bannerPrompt: 'A loaded truck on the Djibouti corridor at dawn, heat shimmer.',
    postingStyle: 'Road updates in Somali; corridor-condition intel.',
    labInterests: ['logistics'],
    dmStyle: 'Offline for days, then a burst.',
    moderationRisk: 'normal',
    activity: 'low',
    testPurpose: 'Djibouti node; mobile-only low-bandwidth long-haul usage pattern.',
  },
  {
    handle: 'luul_dukaan',
    displayName: 'Luul Axmed Weheliye',
    ageBand: '35-44',
    locationCountry: 'US',
    locationCity: 'Minneapolis',
    timezone: 'America/Chicago',
    languages: ['en', 'so'],
    preferredLanguage: 'en',
    lowBandwidth: false,
    oneLine: 'Owns a halal grocery on Lake Street.',
    bio: 'Luul’s Halal Market, Lake Street, Minneapolis. Fresh hilib, camel milk on Fridays, and the good basmati. Second-generation shopkeeper — my mother started with one shelf in 1998.',
    skills: ['sales', 'bookkeeping'],
    interests: ['grocery', 'community-retail'],
    lanes: ['retail', 'agri-food'],
    openTo: ['hiring'],
    availability: 'Store hours.',
    membershipTier: 'free',
    role: 'member',
    isVerifier: false,
    verification: 'unverified',
    accountStatus: 'active',
    completeness: 'full',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Somali-American shopkeeper, 41, behind a bright grocery counter, welcoming.',
    bannerPrompt: 'Grocery shelves with Somali staples: xawaash jars, dates, banana crates.',
    postingStyle: 'Community-notice posts (new stock, Ramadan hours).',
    labInterests: [],
    dmStyle: 'Practical; ends with store hours.',
    moderationRisk: 'normal',
    activity: 'medium',
    testPurpose: 'Member-owned listing (created directly, not claimed); Minneapolis cluster; win post.',
  },
  {
    handle: 'jamaal_bir',
    displayName: 'Jamaal Xasan Faahiye',
    ageBand: '25-34',
    locationCountry: 'SO',
    locationCity: 'Hargeisa',
    timezone: 'Africa/Mogadishu',
    languages: ['so'],
    preferredLanguage: 'so',
    lowBandwidth: true,
    oneLine: 'Welder; gates, doors, and the occasional water tank.',
    bio: null,
    skills: ['welding'],
    interests: ['metalwork'],
    lanes: ['construction'],
    openTo: ['hire_me'],
    availability: 'Daylight hours.',
    membershipTier: 'free',
    role: 'member',
    isVerifier: false,
    verification: 'unverified',
    accountStatus: 'active',
    completeness: 'minimal',
    hasAvatar: false,
    hasBanner: false,
    avatarPrompt: 'Somali welder, 27, protective goggles pushed up, sparks bokeh behind, quiet pride.',
    bannerPrompt: 'A freshly welded ornamental gate leaning on a workshop wall.',
    postingStyle: 'Silent; reacts to trades content.',
    labInterests: [],
    dmStyle: 'Phone number in first reply.',
    moderationRisk: 'normal',
    activity: 'lurker',
    testPurpose: 'Minimal Somali-only trades lurker; gradient avatar.',
  },
  {
    handle: 'cawo_cargo',
    displayName: 'Cawo Daahir Samatar',
    ageBand: '25-34',
    locationCountry: 'SO',
    locationCity: 'Mogadishu',
    timezone: 'Africa/Mogadishu',
    languages: ['so', 'en'],
    preferredLanguage: 'en',
    lowBandwidth: false,
    oneLine: 'Freight coordinator at Mogadishu port; spreadsheet whisperer.',
    bio: 'Freight forwarding ops at the port. I turn container chaos into tidy manifests. Building better tracking sheets for small importers in the Xawilaad Sandbox Lab — logistics needs software love too.',
    skills: ['logistics', 'data analysis', 'sql'],
    interests: ['shipping', 'ports', 'tracking'],
    lanes: ['logistics', 'import-export'],
    openTo: ['collaborating', 'hire_me'],
    availability: 'Post-5pm EAT.',
    membershipTier: 'supporter',
    role: 'member',
    isVerifier: false,
    verification: 'unverified',
    accountStatus: 'active',
    completeness: 'full',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Somali woman, 28, hi-vis vest over abaya, port cranes behind, clipboard confidence.',
    bannerPrompt: 'Mogadishu port containers at golden hour.',
    postingStyle: 'Practical logistics explainers; bridges trade and tech.',
    labInterests: ['logistics', 'fintech'],
    dmStyle: 'Responds with a template.',
    moderationRisk: 'normal',
    activity: 'medium',
    testPurpose: 'Female-in-logistics persona; lab member; supporter; cross-lane search hits.',
  },
  {
    handle: 'guuleed_dhismo',
    displayName: 'Guuleed Maxamuud Cilmi',
    ageBand: '45-54',
    locationCountry: 'KE',
    locationCity: 'Nairobi',
    timezone: 'Africa/Nairobi',
    languages: ['so', 'en', 'sw'],
    preferredLanguage: 'en',
    lowBandwidth: false,
    oneLine: 'Building contractor; 60 houses and counting.',
    bio: 'Contractor across Nairobi and Garissa. Residential builds, honest quotes, finished on time — which in this industry makes me a unicorn. Slowly moving operations back to Mogadishu.',
    skills: ['construction', 'civil engineering', 'project management'],
    interests: ['real-estate', 'diaspora-building'],
    lanes: ['construction', 'real-estate'],
    openTo: ['hiring', 'collaborating'],
    availability: 'Site hours.',
    membershipTier: 'free',
    role: 'member',
    isVerifier: false,
    verification: 'unverified',
    accountStatus: 'active',
    completeness: 'partial',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Somali contractor, 50, hard hat under arm, half-built house behind, seasoned.',
    bannerPrompt: 'Concrete-block house frame against a Nairobi sky.',
    postingStyle: 'Occasional cost-of-materials updates.',
    labInterests: ['construction'],
    dmStyle: 'Quotes in numbered lists.',
    moderationRisk: 'normal',
    activity: 'low',
    testPurpose: 'Construction/real-estate lanes; diaspora-return economics thread participant.',
  },

  // ───────────────────────── culture / media ─────────────────────────
  {
    handle: 'warda_gabay',
    displayName: 'Warda Ismaaciil Duale',
    ageBand: '25-34',
    locationCountry: 'GB',
    locationCity: 'London',
    timezone: 'Europe/London',
    languages: ['so', 'en'],
    preferredLanguage: 'so',
    lowBandwidth: false,
    oneLine: 'Poet writing between two languages and three cities.',
    bio: 'Gabayaa iyo qoraa. Waxaan ku qoraa labada af — gabayga Soomaaliga iyo spoken word-ka Ingiriisiga. My chapbook “Salt Roads / Jidadka Cusbada” came out last year. Waxaan aaminsanahay in erayadu yihiin xawilaad kale: waxay guriga u diraan waxa aanu lacagtu qaadi karin. Performing monthly at the Poetry Café, Covent Garden. Workshops for young writers — first one free, sida shaaha martida.',
    skills: ['content writing', 'copywriting', 'public speaking', 'translation'],
    interests: ['poetry', 'somali-literature', 'spoken-word'],
    lanes: ['creative-arts', 'media'],
    openTo: ['collaborating', 'hire_me'],
    availability: 'Erratic, like inspiration.',
    membershipTier: 'free',
    role: 'member',
    isVerifier: false,
    verification: 'unverified',
    accountStatus: 'active',
    completeness: 'full',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Somali poet, 29, statement earrings, bookshop reading corner, mid-performance gesture.',
    bannerPrompt: 'Handwritten Somali verse over a London-to-Mogadishu map collage.',
    postingStyle: 'Bilingual poems and reflections; long beautiful bios of others in comments.',
    labInterests: ['creative-arts'],
    dmStyle: 'Writes paragraphs worth screenshotting.',
    moderationRisk: 'normal',
    activity: 'medium',
    testPurpose: 'Long bilingual bio rendering; artistic content; popular follow target.',
  },
  {
    handle: 'abwaan_dhool',
    displayName: 'Cabdullaahi Geedi Kaahin (Dhool)',
    ageBand: '65+',
    locationCountry: 'SO',
    locationCity: 'Hargeisa',
    timezone: 'Africa/Mogadishu',
    languages: ['so'],
    preferredLanguage: 'so',
    lowBandwidth: true,
    oneLine: 'Elder poet and oral historian; carries a library in his memory.',
    bio: 'Abwaan. Waxaan xafidaa gabayadii hore — Qaraami ilaa maanta. Wiilashaydu waxay igu barteen telefoonkan si aan dhallinyarada ula wadaago hiddaha. Su’aal kasta oo taariikh ah, halkan ii soo qor.',
    skills: [],
    interests: ['oral-history', 'classical-poetry', 'heritage'],
    lanes: ['creative-arts'],
    openTo: ['mentoring'],
    availability: 'Subaxdii, kabalayga hortiisa.',
    membershipTier: 'free',
    role: 'member',
    isVerifier: false,
    verification: 'community_verified',
    accountStatus: 'active',
    completeness: 'partial',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Somali elder, 72, white koofiyad, henna-tinted beard, seated with cane, profound calm.',
    bannerPrompt: 'An old cassette recorder and handwritten gabay notebooks.',
    postingStyle: 'Occasional gabay excerpts that stop the feed.',
    labInterests: [],
    dmStyle: 'Grandsons transcribe his replies.',
    moderationRisk: 'normal',
    activity: 'low',
    testPurpose: '65+ elder persona; cultural gravity; community-verified; assisted device use.',
  },
  {
    handle: 'idil_warbaahin',
    displayName: 'Idil Cusmaan Salaad',
    ageBand: '25-34',
    locationCountry: 'SO',
    locationCity: 'Mogadishu',
    timezone: 'Africa/Mogadishu',
    languages: ['so', 'en'],
    preferredLanguage: 'en',
    lowBandwidth: false,
    oneLine: 'Independent journalist covering business and reconstruction.',
    bio: 'Freelance journalist, Mogadishu. Business, infrastructure, and who-actually-got-the-contract. Bylines in three outlets, sources in thirty. I ask uncomfortable questions here too — it is a professional habit, not a personal attack.',
    skills: ['content writing', 'research', 'photography'],
    interests: ['journalism', 'reconstruction', 'transparency'],
    lanes: ['media'],
    openTo: ['collaborating'],
    availability: 'Deadline-driven.',
    membershipTier: 'free',
    role: 'member',
    isVerifier: false,
    verification: 'unverified',
    accountStatus: 'active',
    completeness: 'full',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Somali journalist, 30, press lanyard, notebook, city street, appraising look.',
    bannerPrompt: 'A press notebook, recorder and cooling shaah on a café table.',
    postingStyle: 'Probing questions on candidates and platform governance; polls about trust.',
    labInterests: ['media'],
    dmStyle: 'Off the record until stated otherwise.',
    moderationRisk: 'heated',
    activity: 'medium',
    testPurpose: 'Hard-questions persona (reported once, report in_review — dismissible); governance-transparency reader; poll author.',
  },
  {
    handle: 'samatar_sawir',
    displayName: 'Samatar Nuux Yoonis',
    ageBand: '25-34',
    locationCountry: 'QA',
    locationCity: 'Doha',
    timezone: 'Asia/Qatar',
    languages: ['en', 'so', 'ar'],
    preferredLanguage: 'en',
    lowBandwidth: false,
    oneLine: 'Event photographer; weddings, conferences, and one very famous cat.',
    bio: 'Photographer in Doha. Weddings and corporate events pay the bills; street photography feeds the soul.',
    skills: ['photography', 'videography', 'video editing'],
    interests: ['photography', 'events'],
    lanes: ['creative-arts', 'media'],
    openTo: ['hire_me'],
    availability: 'Except wedding season.',
    membershipTier: 'free',
    role: 'member',
    isVerifier: false,
    verification: 'unverified',
    accountStatus: 'active',
    completeness: 'minimal',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Somali photographer, 27, camera strap, Doha skyline bokeh, artistic squint.',
    bannerPrompt: 'A wedding stage draped in gold and teal, shot wide.',
    postingStyle: 'Rare; offers photo tips.',
    labInterests: [],
    dmStyle: 'Portfolio link, then rates.',
    moderationRisk: 'normal',
    activity: 'lurker',
    testPurpose: 'Gulf creative; minimal profile with avatar; RSVP participant.',
  },

  // ───────────────────────── civic / community ─────────────────────────
  {
    handle: 'nuur_samafal',
    displayName: 'Sheekh Nuur Maxamed Cabdi',
    ageBand: '55-64',
    locationCountry: 'SO',
    locationCity: 'Mogadishu',
    timezone: 'Africa/Mogadishu',
    languages: ['so', 'ar'],
    preferredLanguage: 'so',
    lowBandwidth: true,
    oneLine: 'Mosque volunteer coordinating orphan support and food drives.',
    bio: 'Waxaan iskaa wax u qabso ugu shaqeeyaa masjidka xaafadda — taageerada agoomaha, quudinta bilaha barakaysan, iyo isu-keenidda deeqaha. Halkan waxaan ku xiraa dadka doonaya inay wax tabarrucaan iyo kuwa u baahan. Ilaahay mahaddii.',
    skills: ['fundraising', 'leadership'],
    interests: ['charity', 'orphan-support', 'community'],
    lanes: ['nonprofit'],
    openTo: ['collaborating'],
    availability: 'Salaadaha dhexdooda.',
    membershipTier: 'free',
    role: 'member',
    isVerifier: false,
    verification: 'community_verified',
    accountStatus: 'active',
    completeness: 'partial',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Somali sheikh, 60, white khamiis and koofiyad, mosque courtyard, serene benevolence.',
    bannerPrompt: 'Dates and water arranged for iftar rows in a mosque hall.',
    postingStyle: 'Somali community notices; gratitude posts after drives.',
    labInterests: [],
    dmStyle: 'Blesses, then organises.',
    moderationRisk: 'normal',
    activity: 'medium',
    testPurpose: 'Religious/community volunteer; charity-coordination content; trusted no-avatar elder.',
  },
  {
    handle: 'deeq_organiser',
    displayName: 'Deeq Cali Boos',
    ageBand: '35-44',
    locationCountry: 'US',
    locationCity: 'Minneapolis',
    timezone: 'America/Chicago',
    languages: ['en', 'so'],
    preferredLanguage: 'en',
    lowBandwidth: false,
    oneLine: 'Neighbourhood organiser; turns complaints into committees.',
    bio: 'Cedar-Riverside organiser. Tenant rights, small-business permits, city-hall translation — if it involves a clipboard and a petition, I am there. Also the reason our block party has insurance now.',
    skills: ['public speaking', 'leadership', 'fundraising'],
    interests: ['civic-engagement', 'housing', 'local-politics'],
    lanes: ['nonprofit', 'public-sector'],
    openTo: ['collaborating'],
    availability: 'Evenings + city-council Wednesdays.',
    membershipTier: 'supporter',
    role: 'member',
    isVerifier: false,
    verification: 'community_verified',
    accountStatus: 'active',
    completeness: 'full',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Somali-American organiser, 38, flannel over tee, community-hall noticeboard, approachable energy.',
    bannerPrompt: 'A packed community meeting with raised hands.',
    postingStyle: 'Calls-to-action; recaps of civic wins.',
    labInterests: [],
    dmStyle: 'Adds you to a group chat immediately.',
    moderationRisk: 'normal',
    activity: 'medium',
    testPurpose: 'Local-organiser persona; event RSVP driver; supporter without lab.',
  },
  {
    handle: 'koos_kubad',
    displayName: 'Kaahiye Faarax Heybe (Koos)',
    ageBand: '18-24',
    locationCountry: 'CA',
    locationCity: 'Toronto',
    timezone: 'America/Toronto',
    languages: ['en', 'so'],
    preferredLanguage: 'en',
    lowBandwidth: false,
    oneLine: 'Runs a 12-team Somali youth football league.',
    bio: 'Founder of the Dixon Cup — 12 teams, U-13 to U-19, every summer Sunday. Referee, treasurer, kit-washer, and hype man. Looking for sponsors and a second referee before my knees resign.',
    skills: ['leadership', 'fundraising'],
    interests: ['football', 'youth', 'coaching'],
    lanes: ['nonprofit'],
    openTo: ['collaborating'],
    availability: 'Weekends on the pitch.',
    membershipTier: 'free',
    role: 'member',
    isVerifier: false,
    verification: 'unverified',
    accountStatus: 'active',
    completeness: 'full',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Young Somali-Canadian coach, 22, whistle and cap, football pitch, big grin.',
    bannerPrompt: 'Youth football teams lined up at a summer tournament.',
    postingStyle: 'Hype posts about fixtures; win post when registration fills.',
    labInterests: [],
    dmStyle: 'Voice-of-the-group-chat energy.',
    moderationRisk: 'normal',
    activity: 'medium',
    testPurpose: 'Youth-sports organiser; RSVP magnet event; win posts.',
  },
  {
    handle: 'dalmar_dood',
    displayName: 'Dalmar Yuusuf Geelle',
    ageBand: '35-44',
    locationCountry: 'SE',
    locationCity: 'Stockholm',
    timezone: 'Europe/Stockholm',
    languages: ['so', 'sv', 'en'],
    preferredLanguage: 'en',
    lowBandwidth: false,
    oneLine: 'Professional sceptic; asks who audits the auditors.',
    bio: 'Economist by training, contrarian by temperament. I think most diaspora investment schemes are optimism wearing a suit, and I will say so with citations. If your project survives my questions, it deserves your money. Nothing personal — dood wadaag waa dhaqan (debate is culture).',
    skills: ['finance', 'research', 'data analysis'],
    interests: ['economics', 'due-diligence', 'debate'],
    lanes: ['professional-services'],
    openTo: [],
    availability: 'Whenever something needs doubting.',
    membershipTier: 'free',
    role: 'member',
    isVerifier: false,
    verification: 'unverified',
    accountStatus: 'active',
    completeness: 'full',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Somali-Swedish man, 40, sceptical eyebrow, tidy study with economics books, arms crossed.',
    bannerPrompt: 'A magnifying glass over a spreadsheet, dramatic side light.',
    postingStyle: 'Challenging comments on wins and candidates; civil but relentless.',
    labInterests: [],
    dmStyle: 'Debates in DM too; never rude, never satisfied.',
    moderationRisk: 'heated',
    activity: 'medium',
    testPurpose: 'Heated-but-legitimate user: reported and DISMISSED case (mods distinguish critique from abuse).',
  },
  {
    handle: 'xaliimo_hooyo',
    displayName: 'Xaliimo Aadan Cige',
    ageBand: '45-54',
    locationCountry: 'US',
    locationCity: 'Columbus',
    timezone: 'America/New_York',
    languages: ['so', 'en'],
    preferredLanguage: 'so',
    lowBandwidth: false,
    oneLine: 'Mother of five, carer for her father, glue of three group chats.',
    bio: 'Hooyo shan carruur ah, waxaan daryeelaa aabbahay oo da’ weyn. Waxaan halkan ugu jirtaa inaan la socdo bulshada iyo inaan hesho talooyin ku saabsan daryeelka waayeelka qurbaha. Qolka fadhiga ayaan wax ka soo qoraa, shaah gacanta ku haya.',
    skills: ['tutoring'],
    interests: ['elder-care', 'parenting', 'community'],
    lanes: ['health', 'nonprofit'],
    openTo: [],
    availability: 'After bedtime (theirs, not mine).',
    membershipTier: 'free',
    role: 'member',
    isVerifier: false,
    verification: 'unverified',
    accountStatus: 'active',
    completeness: 'partial',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Somali mother, 48, soft garbasaar, living-room lamp light, tired kind eyes.',
    bannerPrompt: 'A family tea tray with five mismatched cups.',
    postingStyle: 'Rarely posts; DMs constantly; asks one caregiving question.',
    labInterests: [],
    dmStyle: 'The real social network: long, warm, daily.',
    moderationRisk: 'normal',
    activity: 'low',
    testPurpose: 'DM-heavy/feed-light usage pattern; caregiver persona; Somali UI.',
  },

  // ───────────────────────── moderation-test personas ─────────────────────────
  {
    handle: 'guhaad_ganax',
    displayName: 'Guhaad Warsame Tall',
    ageBand: '25-34',
    locationCountry: 'SO',
    locationCity: 'Mogadishu',
    timezone: 'Africa/Mogadishu',
    languages: ['so', 'en'],
    preferredLanguage: 'en',
    lowBandwidth: false,
    oneLine: '“Serial entrepreneur” with a new opportunity every week.',
    bio: 'Founder | Visionary | DM me for OPPORTUNITY 🚀🚀 Building wealth for the ummah. Not financial advice.',
    skills: ['marketing', 'sales'],
    interests: ['crypto', 'dropshipping', 'gold'],
    lanes: ['e-commerce'],
    openTo: ['investing'],
    availability: 'Always online, suspiciously.',
    membershipTier: 'free',
    role: 'member',
    isVerifier: false,
    verification: 'unverified',
    accountStatus: 'active',
    completeness: 'partial',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Somali man, 27, sunglasses indoors, rented-looking luxury car backdrop, salesman grin.',
    bannerPrompt: 'Stacks of gold-coloured coins with motivational typography.',
    postingStyle: 'Spammy “opportunity” posts with rocket emoji; reposts after removal.',
    labInterests: [],
    dmStyle: 'Unsolicited pitches to strangers.',
    moderationRisk: 'spammy',
    activity: 'medium',
    testPurpose: 'Spam pipeline: removed post + resolved report + warning notification + AI-flagged second post (hidden, pending HITL) + reported spam DM.',
  },
  {
    handle: 'burhaan_qaylo',
    displayName: 'Burhaan Cabdi Qorane',
    ageBand: '25-34',
    locationCountry: 'GB',
    locationCity: 'Birmingham',
    timezone: 'Europe/London',
    languages: ['en', 'so'],
    preferredLanguage: 'en',
    lowBandwidth: false,
    oneLine: 'Argues in every thread; currently suspended.',
    bio: 'Say it to my face. All of you know nothing about business.',
    skills: [],
    interests: ['arguing'],
    lanes: ['retail'],
    openTo: [],
    availability: 'Too available.',
    membershipTier: 'free',
    role: 'member',
    isVerifier: false,
    verification: 'unverified',
    accountStatus: 'suspended',
    completeness: 'minimal',
    hasAvatar: false,
    hasBanner: false,
    avatarPrompt: 'Somali man, 26, hood up, low light, defiant glare.',
    bannerPrompt: 'None.',
    postingStyle: 'Insults dressed as opinions (pre-suspension).',
    labInterests: [],
    dmStyle: 'Hostile DMs — the reported evidence.',
    moderationRisk: 'heated',
    activity: 'low',
    testPurpose: 'SUSPENDED user: harassment DM report + snapshot + suspend_user mod action + UPHELD appeal + content hidden by author_is_active().',
  },
  {
    handle: 'xaawo_hadal',
    displayName: 'Xaawo Cabdullaahi Madar',
    ageBand: '35-44',
    locationCountry: 'SO',
    locationCity: 'Galkacyo',
    timezone: 'Africa/Mogadishu',
    languages: ['so', 'en'],
    preferredLanguage: 'so',
    lowBandwidth: false,
    oneLine: 'Passionate about everything, especially disagreements.',
    bio: 'Reer Gaalkacyo. Runta waan sheegaa, qofna kama cabsado. Haddii ay ku dhibayso, taladu waa: ha akhrin.',
    skills: ['sales'],
    interests: ['politics', 'business'],
    lanes: ['retail'],
    openTo: [],
    availability: 'Peak argument hours.',
    membershipTier: 'free',
    role: 'member',
    isVerifier: false,
    verification: 'unverified',
    accountStatus: 'active',
    completeness: 'partial',
    hasAvatar: true,
    hasBanner: false,
    avatarPrompt: 'Somali woman, 37, vivid baati, hands mid-gesture, market backdrop, fierce.',
    bannerPrompt: 'A heated tea-shop debate captured mid-motion.',
    postingStyle: 'ALL-CAPS Somali riposte comments; borderline personal.',
    labInterests: [],
    dmStyle: 'Continues the argument from the thread.',
    moderationRisk: 'heated',
    activity: 'medium',
    testPurpose: 'Live mod-queue item: her comment is reported and IN_REVIEW (assigned to a mod, undecided). Also the reporter in the Burhaan case.',
  },
  {
    handle: 'qali_qarsoon',
    displayName: 'Qali Xasan Muuse',
    ageBand: '25-34',
    locationCountry: 'SO',
    locationCity: 'Merca',
    timezone: 'Africa/Mogadishu',
    languages: ['so'],
    preferredLanguage: 'so',
    lowBandwidth: true,
    oneLine: 'Sells home-made spice mixes; writes only in Somali.',
    bio: 'Xawaash iyo suugo hooyo — waxaan ka diraa Marka ilaa Muqdisho. Dalab: fariin ii soo dir.',
    skills: ['sales'],
    interests: ['food', 'spices'],
    lanes: ['agri-food', 'retail'],
    openTo: ['hire_me'],
    availability: 'Duhurkii kadib.',
    membershipTier: 'free',
    role: 'member',
    isVerifier: false,
    verification: 'unverified',
    accountStatus: 'active',
    completeness: 'partial',
    hasAvatar: true,
    hasBanner: false,
    avatarPrompt: 'Somali woman, 30, measuring spice into paper cones, market stall colour burst.',
    bannerPrompt: 'Pyramids of xawaash spices in red, gold and brown.',
    postingStyle: 'Somali-only sales posts that the AI scanner cannot classify.',
    labInterests: [],
    dmStyle: 'Order-taking.',
    moderationRisk: 'needs_review',
    activity: 'low',
    testPurpose: 'HITL Somali lane: her post sits PENDING as ai_uncertain (published, awaiting human review) — the queue’s live item.',
  },

  // ───────────────────────── edge cases ─────────────────────────
  {
    handle: 'tuute_cusub',
    displayName: 'Cabdiqani Maxamed Nuur (Tuute)',
    ageBand: '18-24',
    locationCountry: 'SO',
    locationCity: 'Garowe',
    timezone: 'Africa/Mogadishu',
    languages: ['so'],
    preferredLanguage: 'so',
    lowBandwidth: true,
    oneLine: 'Joined yesterday. Hasn’t touched anything yet.',
    bio: null,
    skills: [],
    interests: [],
    lanes: [],
    openTo: [],
    availability: 'Unknown.',
    membershipTier: 'free',
    role: 'member',
    isVerifier: false,
    verification: 'unverified',
    accountStatus: 'active',
    completeness: 'bare',
    hasAvatar: false,
    hasBanner: false,
    avatarPrompt: 'Somali youth, 19, curious first-day-here expression, plain background.',
    bannerPrompt: 'None.',
    postingStyle: 'None.',
    labInterests: [],
    dmStyle: 'None yet.',
    moderationRisk: 'normal',
    activity: 'none',
    testPurpose: 'Day-zero account: onboarding checklist, empty states, welcome notification from AI helper.',
  },
  {
    handle: 'daahir_maqan',
    displayName: 'Daahir Cusmaan Beyle',
    ageBand: '35-44',
    locationCountry: 'NO',
    locationCity: 'Oslo',
    timezone: 'Europe/Oslo',
    languages: ['no', 'so', 'en'],
    preferredLanguage: 'en',
    lowBandwidth: false,
    oneLine: 'Tried the app, deactivated his account.',
    bio: 'Taking a break from social apps.',
    skills: ['accounting'],
    interests: [],
    lanes: ['professional-services'],
    openTo: [],
    availability: 'Gone.',
    membershipTier: 'free',
    role: 'member',
    isVerifier: false,
    verification: 'unverified',
    accountStatus: 'deactivated',
    completeness: 'partial',
    hasAvatar: false,
    hasBanner: false,
    avatarPrompt: 'Somali-Norwegian man, 36, neutral portrait, slightly out of frame.',
    bannerPrompt: 'None.',
    postingStyle: 'Left one comment, then left.',
    labInterests: [],
    dmStyle: 'Unreachable.',
    moderationRisk: 'normal',
    activity: 'low',
    testPurpose: 'DEACTIVATED lifecycle: his old comment hidden from members (author_is_active), visible to mods; DM partner sees preserved history.',
  },
  {
    handle: 'safiya_aragto',
    displayName: 'Safiya Axmed Gutaale',
    ageBand: '25-34',
    locationCountry: 'GB',
    locationCity: 'Cardiff',
    timezone: 'Europe/London',
    languages: ['en', 'so'],
    preferredLanguage: 'en',
    lowBandwidth: false,
    oneLine: 'Follows everyone, posts nothing, misses nothing.',
    bio: 'Here to watch the community grow. Maybe one day I will post. Today is not that day.',
    skills: ['content writing'],
    interests: ['everything', 'quietly'],
    lanes: ['media'],
    openTo: [],
    availability: 'Scrolling hours.',
    membershipTier: 'free',
    role: 'member',
    isVerifier: false,
    verification: 'unverified',
    accountStatus: 'active',
    completeness: 'partial',
    hasAvatar: true,
    hasBanner: true,
    avatarPrompt: 'Somali woman, 27, oversized cardigan, cosy window seat with phone, observant smile.',
    bannerPrompt: 'A quiet café window with rain and a glowing phone.',
    postingStyle: 'Zero posts; follows and reads everything.',
    labInterests: [],
    dmStyle: 'Sends one fan message to a poet.',
    moderationRisk: 'normal',
    activity: 'lurker',
    testPurpose: 'Pure consumer: max follows, zero posts — following-feed and notification-receiver testing.',
  },
];

/** Convenience: email for a persona/AI helper handle (login convention). */
export function testEmail(handle: string): string {
  return `${handle}@example.com`;
}

/**
 * Every account handle this seeder owns: the personas plus the test AI
 * helpers (NOT the shared `xidig_ai` actor, which belongs to the launch seed).
 * Fixture identity is this handle AND its testEmail() AND users.is_test —
 * never the example.com domain alone. The quarantine migration's backfill list
 * (20260912050000) is pinned to this set by a test.
 */
export function testCommunityFixtureHandles(): string[] {
  return [...TEST_PERSONAS.map((p) => p.handle), ...TEST_AI_HELPERS.map((h) => h.handle)];
}

/** The seed_runs marker labels this seeder writes (never matched by prefix). */
export const TEST_COMMUNITY_MARKER_LABELS = [
  'test-community-v1',
  'test-community-v2',
  'test-community-awards',
] as const;

/** Personas indexed by handle (build-time sanity: handles must be unique). */
export const PERSONAS_BY_HANDLE: ReadonlyMap<string, TestPersona> = new Map(
  TEST_PERSONAS.map((p) => [p.handle, p]),
);
if (PERSONAS_BY_HANDLE.size !== TEST_PERSONAS.length) {
  throw new Error('test-community personas: duplicate handle detected');
}
